# This is a config for E2B sandbox template.
# You can use template ID (j4vouk3dmgl7qt3gh54z) or template name (genly-nextjs-nitin-16) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("genly-nextjs-nitin-16") # Sync sandbox
# sandbox = await AsyncSandbox.create("genly-nextjs-nitin-16") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('genly-nextjs-nitin-16')

team_id = "a5ba7f74-c713-4254-bc23-39f323b2e4da"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "genly-nextjs-nitin-16"
template_id = "j4vouk3dmgl7qt3gh54z"
